#if !canImport(ObjectiveC)
import XCTest

extension ArrayAdditionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayAdditionsTests = [
        ("testCompactMapRemoving", testCompactMapRemoving),
        ("testFlatMapEachCombination", testFlatMapEachCombination),
        ("testMapEachCombination", testMapEachCombination),
        ("testMutableForEach", testMutableForEach),
        ("testReduceEachCombinationInto", testReduceEachCombinationInto),
    ]
}

extension OrderedDefinitionBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedDefinitionBuilderTests = [
        ("testErrorIsReturnedForThrowingFunctionWithLazyUsage", testErrorIsReturnedForThrowingFunctionWithLazyUsage),
        ("testResolverWithCircularDependencyReturnsError", testResolverWithCircularDependencyReturnsError),
        ("testSimpleResolverReturnsCorrectOrder", testSimpleResolverReturnsCorrectOrder),
    ]
}

extension OutputFileContentsBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OutputFileContentsBuilderTests = [
        ("testOutputWithFourSpacesIsCorrect", testOutputWithFourSpacesIsCorrect),
        ("testOutputWithResolvedLazyKeyIsCorrect", testOutputWithResolvedLazyKeyIsCorrect),
        ("testOutputWithTabsIsCorrect", testOutputWithTabsIsCorrect),
        ("testOutputWithTwoSpacesIsCorrect", testOutputWithTwoSpacesIsCorrect),
        ("testOutputWithUnresolvedLazyKeyIsCorrect", testOutputWithUnresolvedLazyKeyIsCorrect),
    ]
}

extension ResolverDefinitionBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResolverDefinitionBuilderTests = [
        ("testDefinitionHasCorrectConfigFunctions", testDefinitionHasCorrectConfigFunctions),
        ("testDefinitionHasCorrectKeys", testDefinitionHasCorrectKeys),
        ("testDefinitionHasCorrectOutput", testDefinitionHasCorrectOutput),
        ("testDefinitionHasCorrectResolverFunctions", testDefinitionHasCorrectResolverFunctions),
        ("testDefinitionHasCorrectTypeChain", testDefinitionHasCorrectTypeChain),
        ("testDefinitionIsReturnedForResolverWithNamespace", testDefinitionIsReturnedForResolverWithNamespace),
        ("testDefinitionIsReturnedWithAnExtension", testDefinitionIsReturnedWithAnExtension),
        ("testErrorIsReturnedForAllKeyMembersThatAreNotTypeAliases", testErrorIsReturnedForAllKeyMembersThatAreNotTypeAliases),
        ("testErrorIsReturnedForKeyThatIsNotAnEnum", testErrorIsReturnedForKeyThatIsNotAnEnum),
        ("testErrorIsReturnedForOutputThatIsNotAnAlias", testErrorIsReturnedForOutputThatIsNotAnAlias),
        ("testErrorIsReturnedIfResolverDeclarationCannotBeFound", testErrorIsReturnedIfResolverDeclarationCannotBeFound),
        ("testErrorIsReturnedIfResolverFunctionContainsNonKeyParam", testErrorIsReturnedIfResolverFunctionContainsNonKeyParam),
        ("testErrorIsReturnedIfResolverHasDuplicateResolverFunctions", testErrorIsReturnedIfResolverHasDuplicateResolverFunctions),
        ("testErrorIsReturnedWhenOutputIsNotAMemberOfKey", testErrorIsReturnedWhenOutputIsNotAMemberOfKey),
        ("testNoDefinitionOrErrorReturnedForNoKey", testNoDefinitionOrErrorReturnedForNoKey),
        ("testNoDefinitionOrErrorReturnedForNoOutput", testNoDefinitionOrErrorReturnedForNoOutput),
    ]
}

extension StringAdditionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringAdditionsTests = [
        ("testDotPathIsExpandedCorrectly", testDotPathIsExpandedCorrectly),
        ("testPrefixAndSuffixAreStripped", testPrefixAndSuffixAreStripped),
        ("testPrefixIsNotStrippedWithoutSuffix", testPrefixIsNotStrippedWithoutSuffix),
        ("testPrefixIsStripped", testPrefixIsStripped),
        ("testSuffixIsNotStrippedWithoutPrefix", testSuffixIsNotStrippedWithoutPrefix),
        ("testSuffixIsStripped", testSuffixIsStripped),
        ("testTildeIsExpandedCorrectly", testTildeIsExpandedCorrectly),
    ]
}

extension TypeAliasDefinitionBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeAliasDefinitionBuilderTests = [
        ("testInvalidTypeAliasReturnsError", testInvalidTypeAliasReturnsError),
        ("testKeyMemberErrorIsCorrect", testKeyMemberErrorIsCorrect),
        ("testOutputErrorIsCorrect", testOutputErrorIsCorrect),
        ("testUnusualTypeAliasReturnsDefinition", testUnusualTypeAliasReturnsDefinition),
        ("testValidTypeAliasReturnsDefinition", testValidTypeAliasReturnsDefinition),
    ]
}

extension XcodeErrorDescriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcodeErrorDescriptionTests = [
        ("testErrorStringIsCorrectWhenPathIsNil", testErrorStringIsCorrectWhenPathIsNil),
        ("testJoinedErrorStringsAreCorrect", testJoinedErrorStringsAreCorrect),
        ("testXcodeErrorStringIsCorrect", testXcodeErrorStringIsCorrect),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayAdditionsTests.__allTests__ArrayAdditionsTests),
        testCase(OrderedDefinitionBuilderTests.__allTests__OrderedDefinitionBuilderTests),
        testCase(OutputFileContentsBuilderTests.__allTests__OutputFileContentsBuilderTests),
        testCase(ResolverDefinitionBuilderTests.__allTests__ResolverDefinitionBuilderTests),
        testCase(StringAdditionsTests.__allTests__StringAdditionsTests),
        testCase(TypeAliasDefinitionBuilderTests.__allTests__TypeAliasDefinitionBuilderTests),
        testCase(XcodeErrorDescriptionTests.__allTests__XcodeErrorDescriptionTests),
    ]
}
#endif
