name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set SourceKit environment variable
      run: echo "::set-env name=LINUX_SOURCEKIT_LIB_PATH::/usr/share/swift/usr/lib/libsourcekitdInProc.so"
    - name: Build
      run: swift build -v
    - name: Generate LinuxMain.swift
      run: swift test --generate-linuxmain
    - name: Run tests
      run: swift test -v
