name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link SourceKit in correct search path
      run: sudo ln -s /usr/share/swift/usr/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so
    - name: Build
      run: swift build -v
    - name: Generate LinuxMain.swift
      run: swift test --generate-linuxmain
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Move coverage file to well-known location
      run: cp $(swift test --show-codecov-path) ./coverage.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.json
        fail_ci_if_error: true
