name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link SourceKit in correct search path
      run: sudo ln -s /usr/share/swift/usr/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so
    - name: Install LLVM
      run: sudo apt-get install -y llvm
    - name: Build
      run: swift build -v
    - name: Generate LinuxMain.swift
      run: swift test --generate-linuxmain
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Covert Swift coverage report to HTML
      run: llvm-cov export -format="html" .build/debug/SettlerPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > ./coverage.html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.html
        fail_ci_if_error: true
